# Generated by Django 4.0.5 on 2022-06-15 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZuulJob',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('job_name', models.TextField(max_length=100)),
                ('job_url', models.URLField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ZuulJobHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(unique=True)),
                ('tests_log_url', models.URLField(max_length=300, null=True)),
                ('duration', models.IntegerField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('event_timestamp', models.DateTimeField(null=True)),
                ('project', models.TextField(max_length=100)),
                ('pipeline', models.TextField(max_length=50)),
                ('result', models.TextField(max_length=10)),
                ('voting', models.BooleanField()),
                ('job_tests', models.TextField(max_length=500)),
                ('job_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devtools.zuuljob')),
            ],
        ),
    ]
