# Generated by Django 4.0.5 on 2022-07-05 12:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('release_id', models.IntegerField(primary_key=True, serialize=False)),
                ('release_name', models.CharField(max_length=30)),
                ('distro', models.CharField(max_length=30)),
                ('dlrn_host', models.CharField(max_length=200)),
                ('dlrn_scheme', models.CharField(max_length=10)),
                ('dlrn_port', models.CharField(max_length=5)),
                ('hashes_count', models.IntegerField()),
                ('source_namespace', models.CharField(max_length=50)),
                ('target_namespace', models.CharField(max_length=50)),
                ('source_registry', models.URLField()),
                ('target_registry', models.URLField()),
                ('target_label', models.CharField(max_length=40)),
                ('source_label', models.CharField(max_length=40)),
                ('criteria', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100, null=True), blank=True, size=None)),
            ],
        ),
    ]
