# Generated by Django 4.0.5 on 2022-07-21 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('release_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('release_name', models.CharField(max_length=30)),
                ('distro', models.CharField(max_length=30)),
                ('dlrn_host', models.URLField()),
                ('hashes_count', models.IntegerField()),
                ('source_namespace', models.CharField(max_length=50)),
                ('target_namespace', models.CharField(max_length=50)),
                ('source_registry', models.URLField()),
                ('target_registry', models.URLField()),
                ('promotions', models.JSONField(null=True)),
            ],
        ),
    ]
