# Generated by Django 4.0.5 on 2022-07-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promoter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='release',
            name='criteria',
        ),
        migrations.RemoveField(
            model_name='release',
            name='source_label',
        ),
        migrations.RemoveField(
            model_name='release',
            name='target_label',
        ),
        migrations.AddField(
            model_name='release',
            name='promotions',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='release',
            name='release_id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
