# Generated by Django 4.0.5 on 2022-07-05 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promoter', '0002_remove_release_criteria_remove_release_source_label_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='release',
            name='dlrn_port',
        ),
        migrations.RemoveField(
            model_name='release',
            name='dlrn_scheme',
        ),
        migrations.AlterField(
            model_name='release',
            name='dlrn_host',
            field=models.URLField(),
        ),
    ]
